package co.salehere.starcard.theme

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.material3.LocalContentColor
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import co.salehere.starcard.R

// MARK: - SF Symbols → Phosphor
//
// iOS ใช้ `Image(systemName:)` ในหลายจุด (ถาดเครื่องมือ · ไอคอนประจำชนิด widget · ปุ่มเล็ก ๆ)
// Android ไม่มี SF Symbols — ตารางนี้จับคู่ชื่อ SF ที่แอปใช้เข้ากับไอคอน Phosphor ที่ความหมายเดียวกัน
// ชื่อที่ไม่อยู่ในตารางตกไปที่ `circle-dashed` ให้เห็นว่ามีอะไรอยู่ตรงนั้น (แล้วค่อยเติมคู่ทีหลัง)

object Symbols {
    private val table: Map<String, Pair<Ph, PhWeight>> = mapOf(
        "xmark" to (Ph.x to PhWeight.bold),
        "xmark.circle.fill" to (Ph.xCircle to PhWeight.fill),
        "checkmark" to (Ph.check to PhWeight.bold),
        "checkmark.seal.fill" to (Ph.sealCheck to PhWeight.fill),
        "seal.fill" to (Ph.sealCheck to PhWeight.fill),
        "plus" to (Ph.plus to PhWeight.bold),
        "pencil" to (Ph.pencilSimple to PhWeight.bold),
        "trash" to (Ph.trash to PhWeight.bold),
        "lock.fill" to (Ph.lockSimple to PhWeight.fill),
        "lock.open" to (Ph.lockOpen to PhWeight.bold),
        "ellipsis" to (Ph.dotsThree to PhWeight.bold),
        "chevron.left" to (Ph.caretLeft to PhWeight.bold),
        "chevron.right" to (Ph.caretRight to PhWeight.bold),
        "chevron.up" to (Ph.caretUpDown to PhWeight.bold),
        "chevron.down" to (Ph.caretDown to PhWeight.bold),
        "play.fill" to (Ph.play to PhWeight.fill),
        "play.rectangle.fill" to (Ph.play to PhWeight.fill),
        "photo" to (Ph.imageSquare to PhWeight.regular),
        "photo.fill" to (Ph.imageSquare to PhWeight.fill),
        "photo.badge.plus.fill" to (Ph.imageSquare to PhWeight.fill),
        "photo.on.rectangle.angled" to (Ph.imageSquare to PhWeight.regular),
        "photo.artframe" to (Ph.imageSquare to PhWeight.regular),
        "photo.stack" to (Ph.squaresFour to PhWeight.fill),
        "camera.fill" to (Ph.camera to PhWeight.fill),
        "camera.viewfinder" to (Ph.camera to PhWeight.regular),
        "person.fill" to (Ph.user to PhWeight.fill),
        "person.crop.square" to (Ph.userCircle to PhWeight.regular),
        "person.crop.square.fill" to (Ph.userCircle to PhWeight.fill),
        "person.crop.rectangle.stack.fill" to (Ph.identificationCard to PhWeight.fill),
        "person.crop.rectangle.fill" to (Ph.identificationCard to PhWeight.fill),
        "person.crop.rectangle.badge.plus" to (Ph.identificationCard to PhWeight.regular),
        "person.and.background.dotted" to (Ph.user to PhWeight.regular),
        "person.and.background.striped.horizontal" to (Ph.user to PhWeight.bold),
        "person.text.rectangle.fill" to (Ph.identificationCard to PhWeight.fill),
        "person.2.fill" to (Ph.usersThree to PhWeight.fill),
        "figure.stand" to (Ph.user to PhWeight.regular),
        "link" to (Ph.link to PhWeight.bold),
        "envelope.fill" to (Ph.envelope to PhWeight.fill),
        "bookmark" to (Ph.bookmark to PhWeight.regular),
        "bookmark.fill" to (Ph.bookmark to PhWeight.fill),
        "arrowshape.turn.up.right.fill" to (Ph.shareFat to PhWeight.fill),
        "square.and.arrow.up" to (Ph.share to PhWeight.bold),
        "arrow.counterclockwise" to (Ph.arrowsClockwise to PhWeight.bold),
        "arrow.uturn.backward" to (Ph.arrowsClockwise to PhWeight.bold),
        "arrow.uturn.forward" to (Ph.arrowsClockwise to PhWeight.bold),
        "arrow.up.left.and.arrow.down.right" to (Ph.caretUpDown to PhWeight.bold),
        "arrow.up.and.down.and.arrow.left.and.right" to (Ph.arrowsClockwise to PhWeight.bold),
        "arrow.left.arrow.right" to (Ph.arrowRight to PhWeight.bold),
        "arrow.triangle.2.circlepath" to (Ph.arrowsClockwise to PhWeight.bold),
        "clock" to (Ph.clock to PhWeight.regular),
        "eyedropper" to (Ph.magicWand to PhWeight.bold),
        "speaker.wave.2.fill" to (Ph.broadcast to PhWeight.fill),
        "forward.end.fill" to (Ph.skipForward to PhWeight.fill),
        "backward.end.fill" to (Ph.skipBack to PhWeight.fill),
        "asterisk" to (Ph.sparkle to PhWeight.bold),
        "quote.opening" to (Ph.quotes to PhWeight.fill),
        "quote.bubble.fill" to (Ph.chatCircleText to PhWeight.fill),
        "bubble.left.fill" to (Ph.chatCircle to PhWeight.fill),
        "tray.full.fill" to (Ph.`package` to PhWeight.fill),
        "square.grid.2x2" to (Ph.squaresFour to PhWeight.regular),
        "square.grid.2x2.fill" to (Ph.squaresFour to PhWeight.fill),
        "square.grid.3x3.fill" to (Ph.squaresFour to PhWeight.fill),
        "circle.grid.3x3.fill" to (Ph.squaresFour to PhWeight.fill),
        "circle.grid.2x1.fill" to (Ph.circleHalf to PhWeight.fill),
        "circle.grid.3x1.fill" to (Ph.circleDashed to PhWeight.fill),
        "rectangle.stack.badge.plus" to (Ph.squaresFour to PhWeight.bold),
        "rectangle.split.3x1.fill" to (Ph.squaresFour to PhWeight.fill),
        "rectangle.split.2x1.fill" to (Ph.squaresFour to PhWeight.fill),
        "rectangle.split.2x2.fill" to (Ph.squaresFour to PhWeight.fill),
        "rectangle.grid.1x2.fill" to (Ph.squaresFour to PhWeight.fill),
        "rectangle.3.group.fill" to (Ph.squaresFour to PhWeight.fill),
        "rectangle.split.3x1" to (Ph.browsers to PhWeight.regular),
        "rectangle.portrait" to (Ph.fileImage to PhWeight.regular),
        "square.stack.fill" to (Ph.squaresFour to PhWeight.fill),
        "square.on.square" to (Ph.browsers to PhWeight.regular),
        "square.fill" to (Ph.squaresFour to PhWeight.fill),
        "square.filled.and.line.vertical.and.square" to (Ph.circleHalf to PhWeight.fill),
        "grid" to (Ph.squaresFour to PhWeight.regular),
        "diamond.fill" to (Ph.sparkle to PhWeight.fill),
        "sun.max.fill" to (Ph.sunHorizon to PhWeight.fill),
        "swirl.circle.righthalf.filled" to (Ph.circleHalf to PhWeight.fill),
        "moon.stars.fill" to (Ph.sparkle to PhWeight.fill),
        "doc.plaintext.fill" to (Ph.clipboardText to PhWeight.fill),
        "drop.fill" to (Ph.circleHalf to PhWeight.fill),
        "textformat" to (Ph.textAlignLeft to PhWeight.bold),
        "textformat.alt" to (Ph.textAlignLeft to PhWeight.bold),
        "textformat.size" to (Ph.textAlignLeft to PhWeight.bold),
        "text.alignleft" to (Ph.textAlignLeft to PhWeight.bold),
        "text.aligncenter" to (Ph.textAlignLeft to PhWeight.bold),
        "text.alignright" to (Ph.textAlignLeft to PhWeight.bold),
        "text.word.spacing" to (Ph.textAlignLeft to PhWeight.regular),
        "text.badge.star" to (Ph.star to PhWeight.fill),
        "text.below.photo.fill" to (Ph.imageSquare to PhWeight.fill),
        "text.line.first.and.arrowtriangle.forward" to (Ph.arrowRight to PhWeight.bold),
        "text.append" to (Ph.textAlignLeft to PhWeight.bold),
        "list.bullet" to (Ph.list to PhWeight.bold),
        "list.number" to (Ph.listChecks to PhWeight.bold),
        "list.bullet.rectangle.fill" to (Ph.listChecks to PhWeight.fill),
        "list.bullet.clipboard.fill" to (Ph.clipboardText to PhWeight.fill),
        "paintpalette" to (Ph.palette to PhWeight.bold),
        "paintbrush.fill" to (Ph.magicWand2 to PhWeight.fill),
        "sparkles" to (Ph.sparkle to PhWeight.fill),
        "heart.text.square.fill" to (Ph.sparkle to PhWeight.fill),
        "number.circle.fill" to (Ph.hash to PhWeight.fill),
        "number.square.fill" to (Ph.hash to PhWeight.fill),
        "chart.bar.fill" to (Ph.chartBar to PhWeight.fill),
        "chart.pie.fill" to (Ph.chartPie to PhWeight.fill),
        "flag.fill" to (Ph.broadcast to PhWeight.fill),
        "rosette" to (Ph.sealCheck to PhWeight.fill),
        "tag" to (Ph.tag to PhWeight.regular),
        "tag.fill" to (Ph.tag to PhWeight.fill),
        "tags.fill" to (Ph.tag to PhWeight.fill),
        "ticket.fill" to (Ph.ticket to PhWeight.fill),
        "lightbulb.fill" to (Ph.lightning to PhWeight.fill),
        "qrcode" to (Ph.qrCode to PhWeight.bold),
        "capsule.portrait.fill" to (Ph.circleHalf to PhWeight.fill),
        "mappin.and.ellipse" to (Ph.mapPin to PhWeight.fill),
        "film.fill" to (Ph.filmStrip to PhWeight.fill),
        "paperclip" to (Ph.link to PhWeight.regular),
        "pin.fill" to (Ph.mapPin to PhWeight.fill),
        "magazine.fill" to (Ph.fileImage to PhWeight.fill),
        "highlighter" to (Ph.pencilSimple to PhWeight.fill),
        "iphone" to (Ph.videoCamera to PhWeight.regular),
        "briefcase.fill" to (Ph.briefcase to PhWeight.fill),
        "hourglass" to (Ph.hourglass to PhWeight.bold),
        "info.circle" to (Ph.info to PhWeight.bold),
        "bell.fill" to (Ph.bell to PhWeight.fill),
        "gift.fill" to (Ph.gift to PhWeight.fill),
        "eye.fill" to (Ph.eye to PhWeight.fill),
        "creditcard.fill" to (Ph.creditCard to PhWeight.fill),
        "building.2.fill" to (Ph.buildings to PhWeight.fill),
        "calendar" to (Ph.calendarBlank to PhWeight.regular),
        "house.fill" to (Ph.house to PhWeight.fill),
        "star.fill" to (Ph.star to PhWeight.fill),
        "star" to (Ph.star to PhWeight.regular),
        "bubble.left.and.bubble.right.fill" to (Ph.chatsCircle to PhWeight.fill),
        "bubble.right" to (Ph.chatCircle to PhWeight.regular),
        "cylinder.split.1x2.fill" to (Ph.database to PhWeight.fill),
        "doc.on.doc" to (Ph.copy to PhWeight.regular),
        "dumbbell.fill" to (Ph.barbell to PhWeight.fill),
        "figure.and.child.holdinghands" to (Ph.baby to PhWeight.fill),
        "fork.knife" to (Ph.forkKnife to PhWeight.regular),
        "gamecontroller.fill" to (Ph.gameController to PhWeight.fill),
        "hand.draw" to (Ph.handPointing to PhWeight.regular),
        "hand.tap" to (Ph.handTap to PhWeight.regular),
        "paintpalette.fill" to (Ph.palette to PhWeight.fill),
        "plus.square.on.square" to (Ph.plusSquare to PhWeight.regular),
        "square.and.arrow.down" to (Ph.downloadSimple to PhWeight.bold),
        "tshirt.fill" to (Ph.tShirt to PhWeight.fill),
        "video.fill" to (Ph.videoCamera to PhWeight.fill),
        "play" to (Ph.play to PhWeight.regular),
        "forward.fill" to (Ph.skipForward to PhWeight.fill),
        "backward.fill" to (Ph.skipBack to PhWeight.fill),
        "phone.fill" to (Ph.phone to PhWeight.fill),
        "phone" to (Ph.phone to PhWeight.regular),
        "message.fill" to (Ph.chatText to PhWeight.fill),
        "envelope" to (Ph.envelope to PhWeight.regular),
        "heart.fill" to (Ph.heart to PhWeight.fill),
        "heart" to (Ph.heart to PhWeight.regular),
        "wand.and.stars" to (Ph.magicWand to PhWeight.fill),
        "mic.fill" to (Ph.microphone to PhWeight.fill),
        "square.and.arrow.up.fill" to (Ph.share to PhWeight.fill),
    )

    fun lookup(sfName: String): Pair<Ph, PhWeight> = table[sfName] ?: (Ph.circleDashed to PhWeight.regular)
}

/** `Image(systemName:)` — วาดไอคอน Phosphor ที่ความหมายตรงกัน ย้อมสีตาม `LocalContentColor` */
@Composable
fun SFSymbol(name: String, size: Float = 14f, tint: Color = LocalContentColor.current, modifier: Modifier = Modifier) {
    val (icon, weight) = Symbols.lookup(name)
    Icon(painterResource(icon.res(weight)), contentDescription = null, tint = tint, modifier = modifier.size(size.dp))
}
